### PR TITLE
Update .gitmodules

### PR DESCRIPTION
**Pull request by zzz6519003**
so that git submodule update runs smoothly

### CODE REVIEW

**Comment by Kjuly** [comment]
I missed it.. Thank you!

**Comment by snowmanzzz** [comment]
老兄最近如何~

**Comment by snowmanzzz** [comment]
@Kjuly

**Comment by Kjuly** [comment]
也就这样～😉

**Comment by snowmanzzz** [comment]
好向往大理，年轻人很多的样子~

**Comment by snowmanzzz** [comment]
还想体验云南的民族风土人情~

**Pull request merged**
